name: alarm_flutter_challenge
description: "A new Flutter project."

publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: '>=3.2.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
 
  cupertino_icons: ^1.0.2
  json_annotation: ^4.8.1
  freezed_annotation: ^2.4.1
  flutter_local_notifications: ^16.3.2
  bloc: ^8.1.2
  flutter_bloc: ^8.1.3
  timezone: ^0.9.2
  alarm: ^3.0.7
  flutter_fgbg: ^0.3.0
  shared_preferences: ^2.2.2
  permission_handler: ^11.2.0
  alarmplayer: ^1.1.1
  vibration: ^1.8.4
  get_it: ^7.6.7
  awesome_notifications_core: ^0.9.1
  awesome_notifications: ^0.9.2


dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0
  freezed: ^2.4.6
  build_runner: ^2.3.3
  json_serializable: ^6.7.1
  
flutter:

  uses-material-design: true

  assets:
  - assets/alarm_audio.wav

  
  
  
  

  
  

  
  

  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
